//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by hMailServer.rc
//
#define IDS_SERVICENAME                 100
#define IDR_HMAILSERVER                 101
#define IDR_INTERFACEWHITELISTADDRESSES 102
#define IDR_INTERFACEWHITELISTADDRESS   103
#define IDR_INTERFACEFORWARDINGRELAYS   104
#define IDR_INTERFACEFORWARDINGRELAY    105
#define IDR_INTERFACESTATUS             113
#define IDR_INTERFACESETTINGS           114
#define IDR_INTERFACEDOMAIN             115
#define IDR_INTERFACEACCOUNTS           116
#define IDR_INTERFACEACCOUNT            117
#define IDR_INTERFACEDATABASE           118
#define IDR_INTERFACEMESSAGE            119
#define IDR_INTERFACEMESSAGES           120
#define IDR_INTERFACEALIASES            121
#define IDR_INTERFACEUTILITIES          122
#define IDR_INTERFACEALIAS              123
#define IDR_INTERFACEATTACHMENT         124
#define IDR_INTERFACEATTACHMENTS        125
#define IDR_INTERFACELOGGING            126
#define IDR_INTERFACEFILTERS            127
#define IDR_INTERFACEFILTER             128
#define IDR_INTERFACEDISTRIBUTIONLISTS  129
#define IDR_INTERFACEDISTRIBUTIONLIST   130
#define IDR_INTERFACEDISTRIBUTIONLISTRECIPIENTS 131
#define IDR_INTERFACEDISTRIBUTIONLISTRECIPIENT 132
#define IDR_INTERFACESECURITYRANGE      133
#define IDR_INTERFACESECURITYRANGES     134
#define IDR_INTERFACEANTIVIRUS          135
#define IDR_INTERFACEROUTE              136
#define IDR_INTERFACEDNSBLACKLISTS      137
#define IDR_INTERFACEDNSBLACKLIST       138
#define IDR_INTERFACEAPPLICATION        139
#define IDR_INTERFACEDOMAINS            140
#define IDR_INTERFACEROUTES             141
#define IDR_INTERFACEROUTEADDRESS       142
#define IDR_INTERFACEROUTEADDRESSES     143
#define IDR_INTERFACERESULT             145
#define IDR_INTERFACECLIENT             146
#define IDR_INTERFACEFETCHACCOUNT       147
#define IDR_INTERFACEFETCHACCOUNTS      148
#define IDR_INTERFACESCRIPTING          149
#define IDR_INTERFACEDOMAINALIASES      150
#define IDR_INTERFACEDOMAINALIAS        151
#define IDR_INTERFACERULES              152
#define IDR_INTERFACERULE               153
#define IDR_INTERFACERULECRITERIA       154
#define IDR_INTERFACERULECRITERIAS      155
#define IDR_INTERFACERULEACTION         156
#define IDR_INTERFACERULEACTIONS        157
#define IDR_INTERFACERECIPIENTS         158
#define IDR_INTERFACERECIPIENT          159
#define IDR_INTERFACECACHE              162
#define IDR_BACKUPMANAGER               163
#define IDR_INTERFACEBACKUPMANAGER      164
#define IDR_INTERFACEBACKUPSETTINGS     165
#define IDR_INTERFACEBACKUP             166
#define IDR_INTERFACEDELIVERYQUEUE      167
#define IDR_INTERFACEGLOBALOBJECTS      168
#define IDR_INTERFACELANGUAGE           169
#define IDR_INTERFACEIMAPFOLDER         170
#define IDR_INTERFACEIMAPFOLDERS        171
#define IDR_INTERFACEEVENTLOG           172
#define IDR_INTERFACESURBLSERVERS       173
#define IDR_INTERFACESURBLSERVER        174
#define IDR_INTERFACEANTISPAM           175
#define IDR_INTERFACEBLOCKEDATTACHMENT  176
#define IDR_INTERFACEBLOCKEDATTACHMENTS 177
#define IDR_INTERFACESERVERMESSAGES     178
#define IDR_INTERFACESERVERMESSAGE      179
#define IDR_INTERFACETCPIPPORT          180
#define IDR_INTERFACETCPIPPORTS         181
#define IDR_INTERFACEGREYLISTINGWHITEADDRESS 182
#define IDR_INTERFACEGREYLISTINGWHITEADDRESSES 183
#define IDR_INTERFACEMESSAGEHEADER      184
#define IDR_INTERFACEMESSAGEHEADERS     185
#define IDR_INTERFACESSLCERTIFICATE     186
#define IDR_INTERFACESSLCERTIFICATES    187
#define IDR_INTERFACEGROUPS             188
#define IDR_INTERFACEGROUP              189
#define IDR_INTERFACEGROUPMEMBERS       190
#define IDR_INTERFACEGROUPMEMBER        191
#define IDR_INTERFACEIMAPFOLDERPERMISSION 192
#define IDR_INTERFACEIMAPFOLDERPERMISSIONS 193
#define IDR_INTERFACEIMAPFOLDERACL      194
#define IDR_INTERFACEDIRECTORIES        195
#define IDR_INTERFACELANGUAGES          196
#define IDR_INTERFACELINKS              197
#define IDR_INTERFACEINCOMINGRELAY      198
#define IDR_INTERFACEINCOMINGRELAYS     199
#define IDR_INTERFACEMESSAGEINDEXING    200
#define IDR_INTERFACEDIAGNOSTICS        201
#define IDR_INTERFACEDIAGNOSTICRESULTS  202
#define IDR_INTERFACEDIAGNOSTICRESULT   203

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        201
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         201
#define _APS_NEXT_SYMED_VALUE           185
#endif
#endif
