//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegressionTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RegressionTests.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From: &quot;Example&quot; &lt;sender@example.com&gt;
        ///To: &lt;test@test.com&gt;
        ///Subject: test
        ///Date: Tue, 7 Oct 2014 10:21:38 +0700
        ///MIME-Version: 1.0
        ///Content-Type: text/html
        ///
        ///&lt;b&gt;HtmlBody&lt;/b&gt;
        ///.
        /// </summary>
        internal static string EmailWith_TextHtmlBody_TextHtmlContentType {
            get {
                return ResourceManager.GetString("EmailWith_TextHtmlBody_TextHtmlContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From: &quot;Example&quot; &lt;sender@example.com&gt;
        ///To: &lt;test@test.com&gt;
        ///Subject: test
        ///Date: Tue, 7 Oct 2014 10:21:38 +0700
        ///MIME-Version: 1.0
        ///
        ///PlainTextBody
        ///.
        /// </summary>
        internal static string EmailWith_TextPlainBody_NoContentType {
            get {
                return ResourceManager.GetString("EmailWith_TextPlainBody_NoContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From: &quot;Test&quot; &lt;test@test.com&gt;
        ///To: &lt;test@test.com&gt;
        ///Subject: test
        ///Date: Thu, 9 Oct 2014 15:53:22 +0200
        ///Content-Type: multipart/alternative;
        ///	boundary=&quot;----=_NextPart_000_005E_01CFE3D9.283B7F70&quot;
        ///X-Mailer: Microsoft Outlook 15.0
        ///Thread-Index: Ac/jyGMJFw9QC1reRDu6jDDRYEKIEw==
        ///Content-Language: sv
        ///
        ///This is a multipart message in MIME format.
        ///
        ///------=_NextPart_000_005E_01CFE3D9.283B7F70
        ///Content-Type: text/plain;
        ///	charset=&quot;us-ascii&quot;
        ///Content-Transfer-Encoding: 7bit
        ///
        ///PlainTextBody
        ///
        ///------=_NextPart_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmailWith_TextPlainBody_TextHtmlBody {
            get {
                return ResourceManager.GetString("EmailWith_TextPlainBody_TextHtmlBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From: &quot;Example&quot; &lt;sender@example.com&gt;
        ///To: &lt;test@test.com&gt;
        ///Subject: test
        ///Date: Tue, 7 Oct 2014 10:21:38 +0700
        ///MIME-Version: 1.0
        ///Content-Type: multipart/mixed; boundary=&quot;----=_NextPart_000_1324_01CFE218.7ABF8CE0&quot;
        ///X-Mailer: Microsoft Outlook 15.0
        ///thread-index: Ac/h3csC7erchVDxTYep5Ouj0dYQ3Q==
        ///Content-Language: en-us
        ///
        ///This is a multipart message in MIME format.
        ///
        ///------=_NextPart_000_1324_01CFE218.7ABF8CE0
        ///Content-Type: multipart/related; boundary=&quot;----=_NextPart_001_1325_01CFE218.7ABF8CE0&quot;
        ///
        ///
        ///---- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmailWith_TextPlainBody_TextHtmlBody_TextHtmlAttachment {
            get {
                return ResourceManager.GetString("EmailWith_TextPlainBody_TextHtmlBody_TextHtmlAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From: &quot;Example&quot; &lt;sender@example.com&gt;
        ///To: &lt;test@test.com&gt;
        ///Subject: test
        ///Date: Tue, 7 Oct 2014 10:21:38 +0700
        ///MIME-Version: 1.0
        ///Content-Type: multipart/mixed; boundary=&quot;----=_NextPart_000_1324_01CFE218.7ABF8CE0&quot;
        ///X-Mailer: Microsoft Outlook 15.0
        ///thread-index: Ac/h3csC7erchVDxTYep5Ouj0dYQ3Q==
        ///Content-Language: en-us
        ///
        ///This is a multipart message in MIME format.
        ///
        ///------=_NextPart_000_1324_01CFE218.7ABF8CE0
        ///Content-Type: multipart/related; boundary=&quot;----=_NextPart_001_1325_01CFE218.7ABF8CE0&quot;
        ///
        ///
        ///---- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmailWith_TextPlainBody_TextHtmlBody_TextPlainAttachment {
            get {
                return ResourceManager.GetString("EmailWith_TextPlainBody_TextHtmlBody_TextPlainAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From: &quot;Example&quot; &lt;sender@example.com&gt;
        ///To: &lt;test@test.com&gt;
        ///Subject: test
        ///Date: Tue, 7 Oct 2014 10:21:38 +0700
        ///MIME-Version: 1.0
        ///Content-Type: text/plain
        ///
        ///PlainTextBody
        ///.
        /// </summary>
        internal static string EmailWith_TextPlainBody_TextPlainContentType {
            get {
                return ResourceManager.GetString("EmailWith_TextPlainBody_TextPlainContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----------------------------------------------------------------------
        ///
        ///The final version of the CSI 6.0 has been released. 
        ///Find out why this is not just another Patch Management solution:
        ///http://secunia.com/blog/325/
        ///
        ///----------------------------------------------------------------------
        ///
        ///TITLE:
        ///Ubuntu update for libxml2
        ///
        ///SECUNIA ADVISORY ID:
        ///SA50800
        ///
        ///VERIFY ADVISORY:
        ///Secunia.com
        ///http://secunia.com/advisories/50800/
        ///Customer Area (Credentials Required)
        ///https://ca.secunia.com/?page=viewad [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SecuniaBody1 {
            get {
                return ResourceManager.GetString("SecuniaBody1", resourceCulture);
            }
        }
    }
}
